# numpy


- 행렬 / 선형대수 / 통계 패키지

- 머신러닝의 이론적 백그라운드는 선형대수와 통계로 이루어져 있다

- 사이킷런 같은 머신러닝 패키지가 넘파이 기반으로 되어 있다


    * 머신러닝 알고리즘이나 사이파이와 같은 과학, 통계 지원용 패키지를 직접 만드는 개발이 아니라면
    넘파이를 상세하기 알 필요는 없다지만, 넘파이를 이해하는 것이 파이썬 기반의 데이타분석과 머신러닝에 중요하다
    
    * 넘파이가 데이타 핸들링에 효율적으로 쉽고 편하고 할 수 없다.
      그러나 데이타 핸들링에 주로 사용하는 판다스도 많은 부분이 넘파이를 기반으로 만들어져 있다.
    
    * ndarray 
        - 넘파이 기반 데이타 타입
        - np.array()   
        
    * 자료형 정리
        + 파이썬(list / tuple)
        + 넘파이(dnarray)
        + 판다스 (dataframe/series)
        
        
    

In [7]:
import numpy as np

list_1 = [1,2,3]
list_2 = [9,8,7]

arr = np.array([list_1,list_2])
print(arr)
print(type(arr))
print(arr.shape)


[[1 2 3]
 [9 8 7]]
<class 'numpy.ndarray'>
(2, 3)


In [10]:
#두번째 행에 두번째 열의 값을 100으로 지정

arr[1][1]=100
print(arr)

[[  1   2   3]
 [  9 100   7]]


In [11]:
?arr  #도움말 보기

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3]])
arr3 = np.array([[1,2,3],[4,5,6]])

print(arr1.shape) #1차원 튜플로 3개의 요소를 가짐 (3,)
print(arr2.shape) #1행 3열의 요소를 가진 2차원 (1, 3)
print(arr3.shape)#2행 3열의 요소를 가진 2차원 (2, 3)


#차원수 확인
print(arr1.ndim,'차원') #1차원
print(arr2.ndim,'차원') #2차원
print(arr3.ndim,'차원')#2차원

(3,)
(1, 3)
(2, 3)
1 차원
2 차원
2 차원


### 자료형

In [17]:
#자료형 확인
print(type(arr))

#요소의 자료형 확인
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [18]:
#요소의 자료형 변경
arr2 = arr.astype(np.float64)
arr2

array([[  1.,   2.,   3.],
       [  9., 100.,   7.]])

In [26]:
list1 = [1,2,3.6]

print(type(list1))
list2 = np.asarray(list1)
print(list2)


<class 'list'>
[1.  2.  3.6]


In [1]:
  # [결과] <U11   : Unicode 문자열 

### nparray를 편리하게 생성

* arange() : 범위를 이용한 배열 만들기
* zeros() : 0으로 채우는 배열 만들기
* ones() : 1로 채우는 배열 만들기

In [29]:
a = np.arange(10)
print(a)

b=np.arange(1,11)
print(b)

c=np.arange(1,11,3)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [34]:
a2 = np.zeros((5,5))  #기본자료형 float
print(a2.dtype)
a2

float64


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
a3 = np.ones((3,4), dtype='int32')
a3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### ndarray의 차원과 크기를 변경 : reshape()

In [42]:
arr = np.arange(10)
print(arr)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [45]:
arr2 = arr.reshape(2,5)
print(arr2)


arr3 = arr2.reshape(3,3) #cannot reshape array of size 10 into shape (3,3)
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,3)

In [47]:
#-1 적용

arr = np.arange(20)
print(arr)

arr2 = arr.reshape(5,-1)
print(arr2)

arr3 = arr.reshape(-1,2)
print(arr3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


### 인덱싱: 특정 데이타 추출

In [49]:
#------------------------------------------ (1) 단일값 출력
import numpy as np
arr = np.arange(1, 11)
print(arr)

## 세번째 요소 추출 ( 0부터 인덱스)
print(arr[2])

## 뒤에서 세번째 요소 추출 ( 뒤에서 인덱스는 -1부터)
print(arr[-3])

[ 1  2  3  4  5  6  7  8  9 10]
3
8


In [53]:
## 1부터 9까지 nparray를 만들고 3행 3열 2차원 구조로 변경한후
## 두번째 행의 세번째 열의 값 추출
arr =np.arange(1,10)
print(arr)

arr2 = arr.reshape(3,3)
print(arr2)

print(arr2[1][2])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [56]:
#------------------------------------------ (2) 슬라이싱 (:)
arr = np.arange(1, 10)
print(arr)

#2번째부터 4번째까지 요소 추출
print(arr[1:4])
#2번째부터 마지막까지 요소 추출
print(arr[1:])
#처음부터 4번째 요소까지 추출
print(arr[:4])



[1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 3 4 5 6 7 8 9]
[1 2 3 4]


In [72]:
# 2차원 배열에서 생성
"""
    1 2 3
    4 5 6
    7 8 9
"""

arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)
    
## 그림에서 1, 2, 4, 5 추출
print(ndarr[:2,:2])


## 그림에서 4, 5, 6, 7, 8, 9 추출
print(ndarr[1:,:])

## 그림에서 2, 3, 5, 6 추출


## 그림에서 1, 4 추출


## 그림에서 전체 요소 추출
print(ndarr[:,:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
# 2차원 ndarray에서 뒤의 오는 인덱스가 없으면 1차원으로 반환
# 3차원 ndarray에서 뒤의 오는 인덱스가 없으면 2차원으로 반환
print(ndarr[1][1])
print(ndarr[1]) #1차원 ndarr


5
[4 5 6]


In [75]:
# 슬라이싱[:]과 인덱스선택을 결합

"""
    1 2 3
    4 5 6
    7 8 9
"""
import numpy as np
arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)

## 그림에서 1, 2, 4, 5 추출
print(ndarr[[0,1],:2])
print(ndarr[:2,:2])
print(ndarr[[0,1],[0,1]]) #인덱스만 쓸경우 [1 5]

## 그림에서 4, 5, 6, 7, 8, 9 추출


## 그림에서 2, 3, 5, 6 추출


## 그림에서 1, 4 추출


## 그림에서 3, 6 추출


# 지금은 너무 간단하다고 여기지만 추후에 데이타에서 많이 헷갈려서 여기서 시간 소요를 많이 한다

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[1 5]


In [79]:
#------------------------------------------ (3) 블린인덱싱
# 조건 필터링과 검색을 같이 하기에 자주 사용

arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)

# 5보다 큰 요소들 추출
print(ndarr > 5) #각요소별 비교 true /false 반환
print(ndarr[ndarr>5])

# 8값 요소를 88로 변경  
ndarr[ndarr==8] =88
print(ndarr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[ 1  2  3]
 [ 4  5  6]
 [ 7 88  9]]
