### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. nparray.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. nparray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [1]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [3]:
# 넘파이 sort
sort1 = np.sort(origin)
print('원본:' ,origin)
print('정렬:' ,sort1)

원본: [3 1 9 7]
정렬: [1 3 7 9]


In [5]:
# 행렬의 sort
sort2 = origin.sort()
print('원본:' ,origin)
print('정렬:' ,sort2)

원본: [1 3 7 9]
정렬: None


### 내림차순 정렬 [::-1]

### 2차원 이상의 행렬에서

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [8]:
arr = np.array([[9, 6, 3],[5, 11, 2]])

#행단위 정렬

sort1 = np.sort(arr,axis=0)
print(sort1)

#열단위 정렬
sort2 = np.sort(arr,axis=1)
print(sort2)

[[ 5  6  2]
 [ 9 11  3]]
[[ 3  6  9]
 [ 2  5 11]]


In [5]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [12]:
arr = np.array([3, 8, 2, 5])

idx = np.argsort(arr)
idx

array([2, 0, 3, 1], dtype=int64)

In [22]:
scores = np.array([66,99,88,44,77])
names = np.array(['홍길동','박길동','김길동','최길동','맹길동'])

#성적순으로 점수와 이름을 매칭하여 출력

idr = np.argsort(scores)
print(idr)

idr2=idr[::-1]
print(idr2)

for a in idr2:
    print(scores[a],names[a])
    
    
       

[3 0 4 2 1]
[1 2 4 0 3]
99 박길동
88 김길동
77 맹길동
66 홍길동
44 최길동
